### ISSUE TITLE
Never saw 1080p

### ISSUE THREAD

**Issue by ValeZAA** [Zggis/dobby#23]
Here: http://media.developer.dolby.com/DolbyVision_Atmos/mp4/iOS_P5_GlassBlowing2_1920x1080%4059.94fps_15200kbps.mp4

**Comment by Zggis** [comment]
Hi ValeZAA,

Per the [FAQ](https://github.com/Zggis/dobby#faq) Dobby does not support 1080p files:

_Right now Dobby does a validation check to make sure the content is 2160p and will fail a job if one of the files is 1080p. While I have seen 1080p HDR content, I have never seen a 1080p Dolby Vision file. So this use case seems rare and I have no way to test it._

**Comment by Zggis** [comment]
Hi ValeZAA,

If I am understanding you correctly, you are referring to my FAQ where I state I have never seen a Dolby Vision 1080p file. The link you posted above does not work for me.

If you are able to correct the link and include the corresponding 1080p HDR mkv file I will take this as a feature request and see if I can  get Dobby to work with 1080p files.

**Comment by ValeZAA** [comment]
Okay, here is yandex drive link: https://disk.yandex.com/d/buNCJyUOfIZYvQ

And another:

https://disk.yandex.com/d/-MmeE9Kuoc56Nw

**Comment by Zggis** [comment]
Can't download either file from yandex, I get client error 'Failed to load resource: net::ERR_NAME_NOT_RESOLVED'

**Comment by ValeZAA** [comment]
`https://mailccsf-my.sharepoint.com/:v:/g/personal/dirizar2_mail_ccsf_edu/EcufL4B7YJRDo548rxLEDC4B7eK6_qvW6o7Kf9rrWWW3qA?e=IqWwSu`

`https://mailccsf-my.sharepoint.com/:v:/g/personal/dirizar2_mail_ccsf_edu/ETlQHxNH-xxNhp0lpvJM-3wB5RdOALGMp-IOnuJJb4U8fA?e=PsMRqN`

**Comment by ValeZAA** [comment]
did you get the files?

**Comment by Zggis** [comment]
Yes, do you have standard HDR versions for either of these files? They are both Dolby vision. Ideally I need an HDR only version of one of them so I can test merging the DV content into the HDR only file.

Otherwise I will see what I can do using a different HDR file.

**Comment by Zggis** [comment]
I tested using these files and another 1080P HDR file I had and confirmed the resulting 1080P file was compatible with HDR and Dolby Vision. So looks like Dobby supports 1080P files.

**Comment by ValeZAA** [comment]
>Yes, do you have standard HDR versions for either of these files? 

Dolby and the guys behind https://youtu.be/LXb3EKWsInQ do. I do not. Thank you for verification.
