### ISSUE TITLE
Convert HDR10+ to DV

### ISSUE THREAD

**Issue by lunks** [Zggis/dobby#27]
My LG TV does not support HDR10+ but HDR10+ and DV seem compatible from what I've read.

**Comment by Zggis** [comment]
Are you having an issue using the Dobby application?

**Comment by Zggis** [comment]
Hi, this application is not intended to convert between HDR10+ and DV. It merges DV and HDR files together to create a single file that has DV, but remains HDR compatible for devices that don't support DV.

**Comment by lunks** [comment]
> Hi, this application is not intended to convert between HDR10+ and DV. It merges DV and HDR files together to create a single file that has DV, but remains HDR compatible for devices that don't support DV.

Wouldn't it be helpful if we could skip needing an additional HDR source, and accomplish the same result with only the DV source?

**Comment by Zggis** [comment]
From what I have read converting DV to HDR10+ requires a specific DV profile, and I believe that profile is normally only available on Blu-ray discs, and at that point if you rip the disc you should be able to get a DV/HDR file without having to use this app anyway.

I have also noticed the popularity of distributing files that are already DV/HDR compatible has increased over the last year making the use case this app was designed for, or the one you are describing above, more and more obsolete. As a result I am less inclined to make significant changes to this app to add support for what I think would be a rare edge case. Sorry.

I will continue to push security patches and dependency updates for Dobby when I can.

**Comment by lunks** [comment]
> From what I have read converting DV to HDR10+ requires a specific DV profile, and I believe that profile is normally only available on Blu-ray discs, and at that point if you rip the disc you should be able to get a DV/HDR file without having to use this app anyway.
> 
> I have also noticed the popularity of distributing files that are already DV/HDR compatible has increased over the last year making the use case this app was designed for, or the one you are describing above, more and more obsolete. As a result I am less inclined to make significant changes to this app to add support for what I think would be a rare edge case. Sorry.
> 
> I will continue to push security patches and dependency updates for Dobby when I can.

Makes sense. I recently had one file with DV only that was hard to come by an HDR version, but it was the first time in months.
