### ISSUE TITLE
Looks like it's not looking recursively?

### ISSUE THREAD

**Issue by twist3dimages** [Zggis/dobby#4]
How do I know if it's working? It closes after about 15 seconds and I know there is media in the folders

Starting DobyApplication using Java 11.0.17 on c26fd3056501 with PID 31 (/app.jar started by user_99_100 in /)
No active profile set, falling back to 1 default profile: "default"
Running Dobby v1.0.3
HikariPool-1 - Starting...
HikariPool-1 - Driver does not support get/set network timeout for connections. (feature not supported)
HikariPool-1 - Start completed.
Scanning /data/media for TV shows...
StartUp (2016) [imdb-tt5028002] is not a MP4 or MKV file, it wil be ignored.
Vikings is not a MP4 or MKV file, it wil be ignored.
The Lord of the Rings - The Rings of Power (2022) [imdb-tt7631058] is not a MP4 or MKV file, it wil be ignored.
House of the Dragon (2022) [imdb-tt11198330] is not a MP4 or MKV file, it wil be ignored.
Stranger Things is not a MP4 or MKV file, it wil be ignored.
You (2018) [imdb-tt7335184] is not a MP4 or MKV file, it wil be ignored.
The Walking Dead is not a MP4 or MKV file, it wil be ignored.
MINDHUNTER is not a MP4 or MKV file, it wil be ignored.
Rick and Morty is not a MP4 or MKV file, it wil be ignored.
Cyberpunk Edgerunners is not a MP4 or MKV file, it wil be ignored.
The Walking Dead (2010) [imdb-tt1520211] is not a MP4 or MKV file, it wil be ignored.
Cyberpunk - Edgerunners (2022) [imdb-tt12590266] is not a MP4 or MKV file, it wil be ignored.
MINDHUNTER (2017) [imdb-tt5290382] is not a MP4 or MKV file, it wil be ignored.
Dexter - New Blood is not a MP4 or MKV file, it wil be ignored.
Stargate is not a MP4 or MKV file, it wil be ignored.
dobby.log is not a MP4 or MKV file, it wil be ignored.
The Witcher is not a MP4 or MKV file, it wil be ignored.
Resident Evil (2022) [imdb-tt9660182] is not a MP4 or MKV file, it wil be ignored.
Reacher is not a MP4 or MKV file, it wil be ignored.
Dexter is not a MP4 or MKV file, it wil be ignored.
Mr Robot is not a MP4 or MKV file, it wil be ignored.
Dahmer - Monster - The Jeffrey Dahmer Story (2022) [imdb-tt13207736] is not a MP4 or MKV file, it wil be ignored.
Dexter - New Blood (2021) [imdb-tt14164730] is not a MP4 or MKV file, it wil be ignored.
American Dad! (2005) [imdb-tt0397306] is not a MP4 or MKV file, it wil be ignored.
No database type set, using meta data indicating: HSQL
No TaskExecutor has been set, defaulting to synchronous executor.
Started DobyApplication in 1.788 seconds (JVM running for 2.248)
Running default command line with: []
Job: [FlowJob: [name=Merge TV Shows]] launched with the following parameters: [{run.id=1}]
Executing step: [0/9 Scan Media]
Step: [0/9 Scan Media] executed in 15ms
Executing step: [1/9 Analyze Active Area of HDR Files]
Step: [1/9 Analyze Active Area of HDR Files] executed in 4ms
Executing step: [2/9 Convert media to HEVC]
Step: [2/9 Convert media to HEVC] executed in 4ms
Executing step: [3/9 Extract RPUs]
Step: [3/9 Extract RPUs] executed in 4ms
Executing step: [4/9 Analyze RPUs]
Step: [4/9 Analyze RPUs] executed in 3ms
Executing step: [5/9 Inject RPUs into HEVCs]
Step: [5/9 Inject RPUs into HEVCs] executed in 4ms
Executing step: [6/9 Validate Merge Compatibility]
Step: [6/9 Validate Merge Compatibility] executed in 4ms
Executing step: [7/9 Generate Results]
Step: [7/9 Generate Results] executed in 4ms
Executing step: [8/9 Validate Results]
Step: [8/9 Validate Results] executed in 4ms
Executing step: [9/9 Cleanup Temporary File]
Cleaning up TEMP directory...
TEMP directory has been deleted!
Step: [9/9 Cleanup Temporary File] executed in 5ms
Job Completed Successfully!
Logs for this job can be found at /data/media/dobby.log
Job: [FlowJob: [name=Merge TV Shows]] completed with the following parameters: [{run.id=1}] and the following status: [COMPLETED] in 146ms
Application will exist in 30s
HikariPool-1 - Shutdown initiated...
HikariPool-1 - Shutdown completed.

**Comment by Zggis** [comment]
As of right now it does not look recursively through subdirectories. Your files would have to be in the top level of the configured directory. Based on your logs it looks like you configured your media library as the working directory and it only found TV show directories and not actual MKV/MP4 files.
I would recommend creating a new empty directory and using that as Dobby's working directory and move files in to it before starting the application. Once the application completes you can move the results out and rinse/repeat with batches of files from the same TV show season. House of the Dragon is one of the shows I have tested it with, so it should work with that one.
